server:
  port: 7788
spring:
  application:
    name: river
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/river?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: admin
#    druid:
#      initial-size: 3
#      min-idle: 3
#      max-active: 20
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      #配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      # 配置监控统计拦截的filters，去掉后监控界面sgl无法统计，"wall"用于防火墙
#      filters: stat ,wall, log4j2
#      filter:
#        stat:
#          slow-sql-millis: 1000
#          log-slow-sql: true #日志输出执行慢的SQL
#          enabled: true
#          db-type: mysql
#      stat-view-servlet:
#        login-username: "admin"
#        login-password: "123456"
#        enabled: true

  servlet:
    multipart:
      max-request-size: "12MB"
      max-file-size: "12MB"
  jackson:
    time-zone: GMT+8
  security:
    oauth2:
      jwt:
        signingKey: river
logging:
  level:
    java:
      sql:
        PreparedStatement: debug
    com:
      springboot: debug
      oryzivora:
        river: debug
  file:
    name: .\logs\${spring.application.name}.log
#    name: /www/wwwlogs/logs/${spring.application.name}.log
#gate:
#  ignore:
#    authentication:
#      startWith: /,/api/auth/signIn,/webSocket/**,/swagger-resources/**,/error,/csrf,/tjpub/**,/v2/api-docs,/swagger-ui**,/doc.html,/webjars/**,/ua/login,/ua/**,/template/**,/druid/**
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO # 0 AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
river:
  app:
    jwtCookieName: river
    jwtSecret: ======================river=Spring===========================
    jwtExpirationMs: 30000